apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  namespace: default
  labels:
    app: presync-job
  annotations:
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
spec:
  template:
    metadata:
      name: presync-job
      labels:
        app: presync-job
    spec:
      containers:
      - name: presync-job
        image: busybox
        command: ["echo", "PreSync Job completed!"]
      restartPolicy: Never